### ISSUE TITLE
Please update for Laravel 10.0

### ISSUE THREAD

**Issue by zenepay** [laracraft-tech/laravel-dynamic-model#1]
Hi, I tried to install to Laravel 10.0 it is not allow. Please update composer if it is workable

**Comment by Sairahcaz** [comment]
Hmm works great for me on a fresh installed Laravel 10 app:

![image](https://user-images.githubusercontent.com/7384870/223980799-c09f2a7d-5224-4f42-9db2-c95ed78057bd.png)

![image](https://user-images.githubusercontent.com/7384870/223980641-06350c3e-4783-4f21-8b01-e4e6d76f5959.png)

**Comment by zenepay** [comment]
I managed it to work manually by downloading and setting composer files. If on here add to the composer.json with require laravel ^10.0, it will help to run composer require … to install.

**Comment by Sairahcaz** [comment]
I added it to composer...

**Comment by zenepay** [comment]
Great. very good support. This works very well.
