### ISSUE TITLE
Add connection to allow different database then default

### ISSUE THREAD

**Issue by paddy01** [laracraft-tech/laravel-dynamic-model#2]
It would be nice to add connection(table_connection?) as option to DynamicModel to allow use of a different database then the default one.
My dynamic tables are in a different table then the default to make it easier to separate them :)

**Comment by Sairahcaz** [comment]
Hi @paddy01, I released version 2 of this package today.
It now requires PHP 8.1.
In version 2 adding the db connection works.

**Comment by paddy01** [comment]
@Sairahcaz  sorry to say but I think something is terribly wrong with version 2.0 :(

I just upgraded to version 2.0 running php 8.2 and laravel 10.5.1 and it only result was that it now sends up the error
"
SQLSTATE[42S02]: Base table or view not found: 1146 Table '***.dynamic_models' doesn't exist (Connection: mysql, SQL: select * from `dynamic_models`)
"
(*** == my database masked)

After downgrading to 1.0 it works as intended.

**Comment by Sairahcaz** [comment]
Hi @paddy01 could you maybe share some code here?

**Comment by paddy01** [comment]
> Hi @paddy01 sorry to hear that, could you maybe share some code here?

Ofc.. something like this is what it looks like
Controller:
```php
    public function index(Table $table)
    {
        $tableName   = $table->name;

        $dynamicTablePrefix = env('DB_PREFIX_2', 'lefnf_');
        $dynDbConnection    = env('DB_CONNECTION_2', 'mysql2');
        $dynTableName       = $dynamicTablePrefix . $tableName;
//       $dynTableName       = $tableName;

        $dynTable = \App::make(
            DynamicModel::class, [
//                'db_connection' => $dynDbConnection,
                'table_name'    => $dynTableName,
            ]
        );
...
        return view('view', array(
            'tableDatas'   => $dynTable->all(),
        ));

``` 

and in my blade template I use tableDatas to fetch data from the table in question
```
                @foreach ($tableDatas as $tableData)
                <tr data-href="{{ route('dtable.edit', array(
                        'iddata'    => $tableData[$tableFields->where('type', 'id')->first()['name']],
                    )) }}
                ">
                @endforeach
``` 
(there are ofc more logic around :) )
This works fine in v1 but not in v2 where it gives the error mentioned earlier.

I don't know where it gets the idea to look for the table dynamic_models .. is this something new i v2 ?
I added a few dumps and stuff to the DynamicModel.php and it seem to be getting all that it should, from what I understand.

**Comment by Sairahcaz** [comment]
I'll check this out this week, want to refactor and improve some stuff here, get back to you soon...

**Comment by Sairahcaz** [comment]
Hi @paddy01, I pushed a new version, feel free to test again!
Notice that a new db connection should be passed like this:

```php
// use another db connection (this one must be defined in your config/database.php file)
$fooOtherDB = App::make(DynamicModel::class, ['baz', 'your-optional-db-connection-name-here']);
```

**Comment by Sairahcaz** [comment]
Hi @paddy01 I definitely need to have a closer look on this. I will have a look at this the next few days...

**Comment by Sairahcaz** [comment]
@paddy01 you are calling the `all` method, since this method is static, it loses the table and connection bindings.
Use `get` instead: `$dynTable->get()` should work...

I'll point that out in the documentation. Could you please revert all your changes and check if it is working with the get method an let me know then?

**Comment by Sairahcaz** [comment]
@paddy01 check out version 3, the static method calls should now work. Consider reading the new docs...

**Comment by paddy01** [comment]
> @paddy01 check out version 3, the static method calls should now work. Consider reading the new docs...

Sorry didn't have time to look at this yesterday but today I upgraded to 3.0 and I almost got it to work.. almost..
now I have to have the dynamic table in the default database and the second for it to work.. but i reads the one in the second database, as it should.
If I remove it I now get
```
LaracraftTech \ LaravelDynamicModel \ DynamicModelException
The table 'dolorum' you provided to the dynamic model does not exists! Please create it first!
```
(dolorum is the dynamic table name)

If I look into debugbar I can see the query
![image](https://user-images.githubusercontent.com/2136198/231752376-1a7a05aa-0e5c-406e-84b3-33b0c1c0dbba.png)

Telescope gives the query as
```
select
  *
from
  information_schema.tables
where
  table_schema = 'MAINTABLE'
  and table_name = 'dolorum'
  and table_type = 'BASE TABLE'
```
while the queries later on that actually looks for the table is actually using the correct connection .. looks like ```DynamicModelFactory.php``` row 59 that is using ```hasTable``` is not using the correct connection hens failing to see that the table exist :/

**Comment by Sairahcaz** [comment]
@paddy01 could you share some code here?
This is working fine for me, on each database connection:

```php
// mysql = default database connection
$foo = app(DynamicModelFactory::class)->create(DynamicModel::class, 'foo', 'mysql');
$foo->find(1)->delete();

// mysql2 = custom defined database connection (config/database.php)
$foo = app(DynamicModelFactory::class)->create(DynamicModel::class, 'foo', 'mysql2');
$foo->find(1)->delete();
```

**Comment by paddy01** [comment]
> @paddy01 could you share some code here? This is working fine for me, on each database connection:

```
$dynDbConnection = 'mysql2';
$dynTableName = 'table';

$dynTable = app(DynamicModelFactory::class)->create(DynamicModel::class, $dynTableName, $dynDbConnection);
dd($dynTable->first());
```
```$dynTable->first()``` works perfectly when the ```$dynTableName``` exists in both default and ```$dynDbConnection``` table but if I remove it from the default table it fails with the errors described earlier.

**Comment by Sairahcaz** [comment]
@paddy01 thanks for your debug help :D 
This should now be fixed in v3.0.1

**Comment by paddy01** [comment]
@Sairahcaz upgraded to 3.0.2 just now and can confirm that it now works with the connection specified! :)

But using prefix doesn't but that ain't important for me at the moment.
Thank you so much for getting separate connection to function and if you decide to work on prefix too I can help you with debugging if needed :)

**Comment by Sairahcaz** [comment]
@paddy01 good to hear that!
If you want you could submit a PR for prefixed tables :D
