### ISSUE TITLE
Unable to use geography types

### ISSUE THREAD

**Issue by AhrimFakhriy** [laracraft-tech/laravel-dynamic-model#6]
Hello, I'm using Postgresql with PostGIS enabled and have a table which contains a column of type geography.

Im getting this error below:

Doctrine\DBAL\Exception  Unknown database type geography requested, Doctrine\DBAL\Platforms\PostgreSQL100Platform may not support it.

May I know if it's supported to use geography types or am I doing something wrong?

**Comment by Sairahcaz** [comment]
Hi @AhrimFakhriy, the problem arises because Doctrine doesn't know how to handle the geography type out of the box, which is a custom type provided by the PostGIS extension for PostgreSQL. Feel free to submit a PR as a fix!
