### ISSUE TITLE
Defning belongsTo Relation in Dynamic Model

### ISSUE THREAD

**Issue by vworld** [laracraft-tech/laravel-dynamic-model#9]
Hi
I have a dynamic model (`dataInFile`) which extends DynamicModel. This model has a reverse one-to-many relation with another model (`UploadedFile`).

```js
class DataInFile extends DynamicModel
{
    use HasFactory;
    public function file(){
        return $this->belongsTo(UploadedFile::class);
    }
}

class UploadedLists extends Model
{
    use HasFactory;
    public function fileData(): HasMany
    {
        $foo = app(DynamicModelFactory::class)->create(DataInFile::class, 'data_1_1');
        return $this->hasMany($foo, 'fileId');
    }
}
```

When I access the `DataInFile` model with 
```js
 $foo = app(DynamicModelFactory::class)->create(DataInFile::class, 'data_1_1');
 $foo->find(1);
```
it works fine and I am able to get the `uploadedFile`.
However the reverse does not work, error being `Base table or view not found: 1146 Table 'my_data_base.data_in_file' doesn't exist `

So is there a way to be able to do this?

Also to make it a little more complicated the name of the table depends on a column in the table `UploadedLists `.

Is this something that can be achieved.

Any help is highly appreciated

**Comment by Sairahcaz** [comment]
Hi @vworld, unfortunately I do not have the time now to test that out. Maybe I can have a look in the next two weeks...

**Comment by Sairahcaz** [comment]
I have not the time to have a closer look at this, feel free to send a PR!

For now I close this issue...
